uses: Platane/snk@v2
  with:
    github_user_name: "sea-breezy"
    # list of files to generate.
    # one file per line. Each output can be customized with options as query string.
    #
    #  supported options:
    #  - palette:     A preset of color, one of [github, github-dark, github-light]
    #  - color_snake: Color of the snake
    #  - color_dots:  Comma separated list of dot colors.
    #                 The first one is for 0 contributions, and then it goes from the lowest to the highest.
    #                 Exactly 5 colors are expected.
  outputs: |
    dist/github-snake.svg
    dist/github-snake-dark.svg?palette=github-dark
    dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9


